[package]
name = "json_packer_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
thiserror = "1"
smallvec = { version = "1", optional = true }

[dev-dependencies]
proptest = "1"
