[package]
name = "json_packer_wasm"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
json_packer_core = { path = "../core" }
serde_json = "1"
wasm-bindgen = "0.2"
js-sys = "0.3"
